---
- name: Create server user
  user:
    name: "{{ "{{" }} server_user {{ "}}" }}"
    groups: wheel,users

- name: Add authorized keys
  become: true
  become_user: "{{ "{{" }} server_user {{ "}}" }}"
  ansible.posix.authorized_key:
    user: "{{ "{{" }} server_user {{ "}}" }}"
    key: "{{ "{{" }} lookup(\"file\", ssh_key_path) {{ "}}" }}"

- name: Secure ssh
  template:
    src: 90-security.conf.j2
    dest: /etc/ssh/sshd_config.d/90-security.conf

- name: Install packages
  ansible.builtin.dnf:
    name: "{{ "{{" }} item {{ "}}" }}"
    state: present
  loop: "{{ "{{" }} packages {{ "}}" }}"