Vagrant.configure("2") do |config|
  config.vm.box = "fedora/39-cloud-base"

  config.ssh.username = "root"
  config.ssh.insert_key = "true"

  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 1024
    libvirt.cpus = 2
    libvirt.nested = true
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "main.yml"
  end
end
