Vagrant.configure("2") do |config|
  config.vm.box = "fedora/39-cloud-base"

  config.ssh.username = "root"
  config.ssh.insert_key = "true"

  config.vm.provider "libvirt" do |virt|
    virt.memory = 1024
    virt.cpus = 2
    virt.nested = true
  end
end
